---
- name: Prepare
  hosts: all
  become: yes
  tasks:
    - name: Ubuntu/Debian | refresh apt repository
      ansible.builtin.apt:
        name: acl
        update_cache: yes
      when: ansible_pkg_mgr == "apt"
