---
- name: Verify
  hosts: all
  tasks:
    - name: Windows | Git should be functional
      ansible.windows.win_command: git version
      register: git_result
      changed_when: false

    - name: Windows | Git lfs should be functional
      ansible.windows.win_command: git lfs version
      register: git_lfs_result
      changed_when: false

    - name: Windows | Verify commands outputs
      ansible.builtin.assert:
        that:
          - git_result.rc == 0
          - git_lfs_result.rc == 0
        success_msg: "All tests passed"
