---
- name: Verify
  hosts: all
  tasks:
    - name: FreeBSD | Git should be functional
      ansible.builtin.command: git version
      register: git_result
      changed_when: false

    - name: FreeBSD | Git lfs should be functional
      ansible.builtin.command: git lfs version
      register: git_lfs_result
      changed_when: false

    - name: FreeBSD | Verify commands outputs
      ansible.builtin.assert:
        that:
          - git_result.rc == 0
          - git_lfs_result.rc == 0
        success_msg: "All tests passed"
